Lpd 381-review-gha (#8)
* Update circleci/trigger/action.yml in order to check for a specific workflow status to finish

* Update circleci/trigger/action.yml in order to check for a specific workflow status to finish

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

* updating file names and adding version number on action calls

diff --git a/circleci/trigger/action.yml b/circleci/trigger/action.yml
--- a/circleci/trigger/action.yml
+++ b/circleci/trigger/action.yml
@@ -18,6 +18,10 @@ inputs:
     description: 'Wait for CircleCI pipeline to complete'
     required: true
     default: 'false'
+  docker_build_job_name:
+    description: 'Name of the product`s job that build and push the application`s docker image'
+    required: true
+    default: 'docker-build-and-push'
 
 outputs:
   cci_response:
@@ -46,20 +50,22 @@ runs:
       env:
         CCI_RESPONSE: ${{steps.trigger_cci.outputs.cci_response}}
         CCI_TOKEN: ${{ inputs.cci_token }}
+        CCI_BUILD_NAME: ${{ inputs.docker_build_job_name }}
       run: |
         echo "Waiting 30 seconds before start checking CircleCI status."
         echo "Check on https://app.circleci.com/pipelines/github/labforward/${{ github.event.repository.name }}"
         sleep 30
-        STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -r '.items[].status')
+        STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -Mre ".items[] | select(.name == \"${CCI_BUILD_NAME}\") | .status"  || echo '"circleci_curl_fail"')
         while [[ $STATUS = 'running' ]]; do
           echo "Pipeline status is $STATUS"
           sleep 10
-          STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -r '.items[].status')
+          STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -Mre ".items[] | select(.name == \"${CCI_BUILD_NAME}\") | .status" || echo '"circleci_curl_fail"')
         done
         
         if [[ $STATUS = 'success' ]]; then
           echo 'Build completed successfully!'
           exit 0
         fi
+        echo $STATUS
         echo 'Build failed'
         exit 1
