updating file names and adding version number on action calls

diff --git a/circleci/trigger/action.yml b/circleci/trigger/action.yml
--- a/circleci/trigger/action.yml
+++ b/circleci/trigger/action.yml
@@ -18,6 +18,10 @@ inputs:
     description: 'Wait for CircleCI pipeline to complete'
     required: true
     default: 'false'
+  docker_build_job_name:
+    description: 'Name of the product`s job that build and push the application`s docker image'
+    required: true
+    default: 'docker-build-and-push'
 
 outputs:
   cci_response:
@@ -50,11 +54,11 @@ runs:
         echo "Waiting 30 seconds before start checking CircleCI status."
         echo "Check on https://app.circleci.com/pipelines/github/labforward/${{ github.event.repository.name }}"
         sleep 30
-        STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq '.items[] | select(.name == "build-and-push-dev-images") | .status')
+        STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -Me '.items[] | select(.name == "${{ input.docker_build_job_name }}") | .status' || echo '"circleci_curl_fail"')
         while [[ $STATUS = 'running' ]]; do
           echo "Pipeline status is $STATUS"
           sleep 10
-          STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq '.items[] | select(.name == "build-and-push-dev-images") | .status')
+          STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -Me '.items[] | select(.name == "${{ input.docker_build_job_name }}") | .status' || echo '"circleci_curl_fail"')
         done
         
         if [[ $STATUS = 'success' ]]; then
